services:
  cobalt:
    image: ghcr.io/duplicake-fyi/cobalt:latest
    build:
      context: .
      target: combined
    init: true
    restart: unless-stopped
    ports:
      - "2841:2841"
    environment:
      API_URL: "http://localhost:2841/"
      API_BASE_PATH: "/api"
      API_LISTEN_ADDRESS: "127.0.0.1"
